### ISSUE TITLE
点击全选时，父组件中绑定的model数组，在父组件的change方法中打印出的数据不对

### ISSUE THREAD

**Issue by stevenolan** [hufei1993/el-select-all#11]

**Comment by fred-hu** [comment]
能不能提供下代码或则截图

**Comment by stevenolan** [comment]
![微信截图_20240816093445](https://github.com/user-attachments/assets/65d313da-675a-45c5-909e-ddb0fc3d3d83)
![微信截图_20240816093539](https://github.com/user-attachments/assets/51b8ab27-d849-44ad-b02f-13b4ca51aefa)
![微信截图_20240816093826](https://github.com/user-attachments/assets/df3e5c65-e6e8-4a50-a0b7-22bf53309424)

我全选时，在父组件change方法中打印绑定的model，应该是全部选项，可是空数组，取消全选时应该打印空数组，可是打印出来全部选项，好像反过来了。

**Comment by fred-hu** [comment]
onChange 方法中的 val 和 this.storeCodes 可能不一致的原因是 Vue 的数据绑定和事件处理机制。val 是事件处理函数接收到的参数，而 this.storeCodes 是组件的状态，它在事件触发后可能还没有完全更新。这种情况通常发生在异步更新中。

在 Vue 中，数据更新是异步的，这意味着当你在事件处理函数中访问 this.storeCodes 时，它可能还没有被更新到最新的值。

要确保 val 和 this.storeCodes 一致，可以考虑以下方法：

1.使用 nextTick: 确保在 DOM 更新完成后执行某些操作。

```
methods: {
  onChange(val) {
    console.log(val);
    this.$nextTick(() => {
      console.log(333, this.storeCodes);
    });
  }
}
```
2.直接使用 val: 如果你只需要在 onChange 方法中处理最新的值，直接使用 val 而不依赖 this.storeCodes。

**Comment by stevenolan** [comment]
可是我在点击单独某个选项时，打印出来是对的，就是全选点击有点问题

**Comment by fred-hu** [comment]
fixed on v0.3.0
